---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: metrics-demo
  namespace: dev
#   annotations:
#     flux.weave.works/automated: 'false'
#     flux.weave.works/tag.podinfod: glob:*
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metrics-demo
  template:
    metadata:
      labels:
        app: metrics-demo
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: metrics-demod
        image: quay.io/brice/metrics-demo:latest
        # command:
        # - ./metrics-demo
        # - --port=3000
        ports:
        - containerPort: 3000
#         readinessProbe:
#           httpGet:
#             path: /readyz
#             port: 3000
#           initialDelaySeconds: 1
#           periodSeconds: 5
#           failureThreshold: 1
#         livenessProbe:
#           httpGet:
#             path: /healthz
#             port: 3000
#           initialDelaySeconds: 1
#           periodSeconds: 10
#           failureThreshold: 2
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"

